const exports = (module.exports = {});

exports.companies = [
    { companyName: 'Bedrift 1', disabled: true },
    { companyName: 'Bedrift 2' },
];

exports.companiesWithMessageCount = [
    {
        organizationName: 'Bedriften',
        organizationNumber: '912602370',
        quantityUnprocessedMessages: 5,
    },
    {
        organizationName: 'Sønn & co',
        organizationNumber: '812602372',
        quantityUnprocessedMessages: 3,
    },
    {
        organizationName: 'Beslag skytter',
        organizationNumber: '812602552',
        quantityUnprocessedMessages: 1,
    },
    {
        organizationName: 'Rør og sånt',
        organizationNumber: '812602399',
        quantityUnprocessedMessages: 7,
    },
    {
        organizationName: 'Kaffekoppen',
        organizationNumber: '812602222',
        quantityUnprocessedMessages: 8,
    },
    {
        organizationName: 'Sats',
        organizationNumber: '809602772',
        quantityUnprocessedMessages: 2,
    },
];

exports.yrker = [
    { kode: '5', beskrivelse: 'Ukjent yrke oppgitt' },
    { kode: '6', beskrivelse: 'Kontor' },
    { kode: '7', beskrivelse: 'Service' },
    { kode: '8', beskrivelse: 'Fysisk arbeid' },
    { kode: '9', beskrivelse: '3D Animatør' },
    { kode: '10', beskrivelse: '3D Artist' },
    { kode: '11', beskrivelse: '3D Designer' },
    { kode: '12', beskrivelse: 'Abonnementselger' },
    { kode: '13', beskrivelse: 'Abonnementsjef' },
    { kode: '14', beskrivelse: 'Account manager' },
    { kode: '15', beskrivelse: 'Addiktolog' },
    { kode: '16', beskrivelse: 'Adjunkt' },
    { kode: '17', beskrivelse: 'Adjutant' },
    { kode: '18', beskrivelse: 'Administrasjonsdirektør' },
    { kode: '19', beskrivelse: 'Administrasjonskonsulent' },
    { kode: '20', beskrivelse: 'Administrasjonssekretær' },
    { kode: '21', beskrivelse: 'Administrasjonssjef' },
    { kode: '22', beskrivelse: 'Administrativ leder' },
    { kode: '23', beskrivelse: 'Administrerende direktør' },
    { kode: '24', beskrivelse: 'Admiral' },
    { kode: '25', beskrivelse: 'Advokat' },
    { kode: '26', beskrivelse: 'Advokatfullmektig' },
    { kode: '27', beskrivelse: 'Advokatsekretær' },
    { kode: '28', beskrivelse: 'Aerobicinstruktør' },
    { kode: '29', beskrivelse: 'Afis-fullmektig' },
    { kode: '30', beskrivelse: 'Agent' },
    { kode: '31', beskrivelse: 'Agronom' },
    { kode: '32', beskrivelse: 'Agrotekniker' },
    { kode: '33', beskrivelse: 'Airpurser' },
    { kode: '34', beskrivelse: 'Airsteward' },
    { kode: '35', beskrivelse: 'Akademiker' },
    { kode: '36', beskrivelse: 'Akrobat' },
    { kode: '37', beskrivelse: 'Aksjemegler' },
    { kode: '38', beskrivelse: 'Aktivitetsformidler' },
    { kode: '39', beskrivelse: 'Aktivitetskoordinator' },
    { kode: '40', beskrivelse: 'Aktivitør' },
    { kode: '41', beskrivelse: 'Aktmodell' },
    { kode: '42', beskrivelse: 'Aktuar' },
    { kode: '43', beskrivelse: 'Akupunktør' },
    { kode: '44', beskrivelse: 'Akvakulturarbeider' },
    { kode: '45', beskrivelse: 'Alarmmontør' },
    { kode: '46', beskrivelse: 'Alarmoperatør' },
    { kode: '47', beskrivelse: 'Alarmsentralleder' },
    { kode: '48', beskrivelse: 'Aldershjemsbestyrer' },
    { kode: '49', beskrivelse: 'Altmuligmann' },
    { kode: '50', beskrivelse: 'Amanuensis' },
    { kode: '51', beskrivelse: 'Ambassaderåd' },
    { kode: '52', beskrivelse: 'Ambassadesekretær' },
    { kode: '53', beskrivelse: 'Ambassadør' },
    { kode: '54', beskrivelse: 'Ambulansepersonell' },
    { kode: '55', beskrivelse: 'Analytiker' },
    { kode: '56', beskrivelse: 'Andrestyrmann' },
    { kode: '57', beskrivelse: 'Anestesilaborant' },
    { kode: '58', beskrivelse: 'Anestesilege' },
    { kode: '59', beskrivelse: 'Anestesisykepleier' },
    { kode: '60', beskrivelse: 'Animatør' },
    { kode: '61', beskrivelse: 'Anleggsarbeider' },
    { kode: '62', beskrivelse: 'Anleggsdykker' },
    { kode: '63', beskrivelse: 'Anleggsgartner' },
    { kode: '64', beskrivelse: 'Anleggsleder' },
    { kode: '65', beskrivelse: 'Anleggsmaskinfører' },
    { kode: '66', beskrivelse: 'Anleggsmaskinmekaniker' },
    { kode: '67', beskrivelse: 'Anleggsmaskinreparatør' },
    { kode: '68', beskrivelse: 'Anleggsmekaniker' },
    { kode: '69', beskrivelse: 'Anleggsoperatør' },
    { kode: '70', beskrivelse: 'Annonsekonsulent' },
    { kode: '71', beskrivelse: 'Annonsesjef' },
    { kode: '72', beskrivelse: 'Antenneteknikker' },
    { kode: '73', beskrivelse: 'Antikvar' },
    { kode: '74', beskrivelse: 'Apoteker' },
    { kode: '75', beskrivelse: 'Apotekmedarbeider' },
    { kode: '76', beskrivelse: 'Apotektekniker' },
    { kode: '77', beskrivelse: 'Arbeidsavklaringspenger' },
    { kode: '78', beskrivelse: 'Arbeidsdirektør' },
    { kode: '79', beskrivelse: 'Arbeidsformidler' },
    { kode: '80', beskrivelse: 'Arbeidsledig' },
    { kode: '81', beskrivelse: 'Arbeidsmiljøsjef' },
    { kode: '82', beskrivelse: 'Arbeidspsykolog' },
    { kode: '83', beskrivelse: 'Arbeidssøker' },
    { kode: '84', beskrivelse: 'Area manager' },
    { kode: '85', beskrivelse: 'Area sales manager' },
    { kode: '86', beskrivelse: 'Arealplanlegger' },
    { kode: '87', beskrivelse: 'Arkeolog' },
    { kode: '88', beskrivelse: 'Arkitekt' },
    { kode: '89', beskrivelse: 'Arkivar' },
    { kode: '90', beskrivelse: 'Arkivmedarbeider' },
    { kode: '91', beskrivelse: 'Arkivsjef' },
    { kode: '92', beskrivelse: 'Aromaterapeut' },
    { kode: '93', beskrivelse: 'Arrangementssjef' },
    { kode: '94', beskrivelse: 'Arrestforvarer' },
    { kode: '95', beskrivelse: 'Art director' },
    { kode: '96', beskrivelse: 'Asfaltarbeider' },
    { kode: '97', beskrivelse: 'Assistent sfo' },
    { kode: '98', beskrivelse: 'Assistent skole' },
    { kode: '99', beskrivelse: 'Assistentlærer' },
    { kode: '100', beskrivelse: 'Assisterende banksjef' },
    { kode: '101', beskrivelse: 'Assisterende borer' },
    { kode: '102', beskrivelse: 'Assisterende butikksjef' },
    { kode: '103', beskrivelse: 'Assisterende byfogd' },
    { kode: '104', beskrivelse: 'Assisterende direktør' },
    { kode: '105', beskrivelse: 'Assisterende etatsjef' },
    { kode: '106', beskrivelse: 'Assisterende forvaltningssjef' },
    { kode: '107', beskrivelse: 'Assisterende fylkesarbeidssjef' },
    { kode: '108', beskrivelse: 'Assisterende fylkeshelsesjef' },
    { kode: '109', beskrivelse: 'Assisterende fylkeslege' },
    { kode: '110', beskrivelse: 'Assisterende fylkesmann' },
    { kode: '111', beskrivelse: 'Assisterende fylkesrådmann' },
    { kode: '112', beskrivelse: 'Assisterende fylkessykehussjef' },
    { kode: '113', beskrivelse: 'Assisterende fylkestannlege' },
    { kode: '114', beskrivelse: 'Assisterende kjøkkensjef' },
    { kode: '115', beskrivelse: 'Assisterende kringkastingssjef' },
    { kode: '116', beskrivelse: 'Assisterende overjordmor' },
    { kode: '117', beskrivelse: 'Assisterende overlege' },
    { kode: '118', beskrivelse: 'Assisterende riksadvokat' },
    { kode: '119', beskrivelse: 'Assisterende rådmann' },
    { kode: '120', beskrivelse: 'Assisterende sjefflygeleder' },
    { kode: '121', beskrivelse: 'Assisterende sjefspsykolog' },
    { kode: '122', beskrivelse: 'Assisterende sjefstråleterapeut' },
    { kode: '123', beskrivelse: 'Assisterende sjefsykepleier' },
    { kode: '124', beskrivelse: 'Assisterende sysselmann' },
    { kode: '125', beskrivelse: 'Assurandør' },
    { kode: '126', beskrivelse: 'Astrofysiker' },
    { kode: '127', beskrivelse: 'Astrolog' },
    { kode: '128', beskrivelse: 'Astronom' },
    { kode: '129', beskrivelse: 'Atomfysiker' },
    { kode: '130', beskrivelse: 'Attache' },
    { kode: '131', beskrivelse: 'Attføringskonsulent' },
    { kode: '132', beskrivelse: 'Audiograf' },
    { kode: '133', beskrivelse: 'Audiometriassistent' },
    { kode: '134', beskrivelse: 'Audiopedagog' },
    { kode: '135', beskrivelse: 'Auksjonarius' },
    { kode: '136', beskrivelse: 'Au-Pair' },
    { kode: '137', beskrivelse: 'Automatiker' },
    { kode: '138', beskrivelse: 'Automatikkmekaniker' },
    { kode: '139', beskrivelse: 'Automatiseringsmontør' },
    { kode: '140', beskrivelse: 'Automatiseringstekniker' },
    { kode: '141', beskrivelse: 'Autorisert finansiell rådgiver' },
    { kode: '142', beskrivelse: 'Autorisert regnskapsfører' },
    { kode: '143', beskrivelse: 'Avdelingsdirektør' },
    { kode: '144', beskrivelse: 'Avdelingsleder' },
    { kode: '145', beskrivelse: 'Avdelingsoverlege' },
    { kode: '146', beskrivelse: 'Avdelingspsykolog' },
    { kode: '147', beskrivelse: 'Avdelingssjef' },
    { kode: '148', beskrivelse: 'Avisbud' },
    { kode: '149', beskrivelse: 'Avløser' },
    { kode: '150', beskrivelse: 'Badevakt' },
    { kode: '151', beskrivelse: 'Baker' },
    { kode: '152', beskrivelse: 'Bakkemannskap' },
    { kode: '153', beskrivelse: 'Bakteriolog' },
    { kode: '154', beskrivelse: 'Ballettdanser' },
    { kode: '155', beskrivelse: 'Ballettpedagog' },
    { kode: '156', beskrivelse: 'Bandasjist' },
    { kode: '157', beskrivelse: 'Banearbeider' },
    { kode: '158', beskrivelse: 'Banemester' },
    { kode: '159', beskrivelse: 'Banemontør' },
    { kode: '160', beskrivelse: 'Baneregionsjef' },
    { kode: '161', beskrivelse: 'Banereperatør' },
    { kode: '162', beskrivelse: 'Baneservicesjef' },
    { kode: '163', beskrivelse: 'Banesjef' },
    { kode: '164', beskrivelse: 'Bankanalytiker' },
    { kode: '165', beskrivelse: 'Bankassistent' },
    { kode: '166', beskrivelse: 'Bankdirektør' },
    { kode: '167', beskrivelse: 'Bankfunksjonær' },
    { kode: '168', beskrivelse: 'Bankkasserer' },
    { kode: '169', beskrivelse: 'Bankkonsulent' },
    { kode: '170', beskrivelse: 'Bankrådgiver' },
    { kode: '171', beskrivelse: 'Banksjef' },
    { kode: '172', beskrivelse: 'Barista' },
    { kode: '173', beskrivelse: 'Barkeeper' },
    { kode: '174', beskrivelse: 'Barne- og ungdomsarbeider' },
    { kode: '175', beskrivelse: 'Barnehageassistent' },
    { kode: '176', beskrivelse: 'Barnehagekonsulent' },
    { kode: '177', beskrivelse: 'Barnehagelærer' },
    { kode: '178', beskrivelse: 'Barnehagestyrer' },
    { kode: '179', beskrivelse: 'Barnehjemsbestyrer' },
    { kode: '180', beskrivelse: 'Barnelege' },
    { kode: '181', beskrivelse: 'Barneombud' },
    { kode: '182', beskrivelse: 'Barneparkleder' },
    { kode: '183', beskrivelse: 'Barnepleier' },
    { kode: '184', beskrivelse: 'Barnevernskonsulent' },
    { kode: '185', beskrivelse: 'Barnevernskurator' },
    { kode: '186', beskrivelse: 'Barnevernspedagog' },
    { kode: '187', beskrivelse: 'Barnevernssjef' },
    { kode: '188', beskrivelse: 'Bartender' },
    { kode: '189', beskrivelse: 'Baseoperatør' },
    { kode: '190', beskrivelse: 'Basketballtrener' },
    { kode: '191', beskrivelse: 'Bedriftsrådgiver' },
    { kode: '192', beskrivelse: 'Bedriftsøkonom' },
    { kode: '193', beskrivelse: 'Befal' },
    { kode: '194', beskrivelse: 'Befrakter' },
    { kode: '195', beskrivelse: 'Befraktningssjef' },
    { kode: '196', beskrivelse: 'Begravelsesbyråarbeider' },
    { kode: '197', beskrivelse: 'Bemanningskoordinator' },
    { kode: '198', beskrivelse: 'Bensinstasjon medarbeider ' },
    { kode: '199', beskrivelse: 'Bergfagarbeider' },
    { kode: '200', beskrivelse: 'Bergmester' },
    { kode: '201', beskrivelse: 'Bergtekniker' },
    { kode: '202', beskrivelse: 'Bergverksarbeider' },
    { kode: '203', beskrivelse: 'Betongarbeider' },
    { kode: '204', beskrivelse: 'Betongpumpeoperatør' },
];
