module.exports = {
    rules: {
        'type-empty': [2, 'never'],
        'scope-enum': [
            2,
            'always',
            [
                'release',
                'eslint-config-ffe',
                'eslint-config-ffe-base',
                'stylelint-config-ffe',
                'ffe-accordion',
                'ffe-accordion-react',
                'ffe-account-selector-react',
                'ffe-buttons',
                'ffe-buttons-react',
                'ffe-cards',
                'ffe-cards-react',
                'ffe-chart-donut-react',
                'ffe-checkbox-react',
                'ffe-context-message',
                'ffe-context-message-react',
                'ffe-core',
                'ffe-core-react',
                'ffe-datepicker',
                'ffe-datepicker-react',
                'ffe-form',
                'ffe-form-react',
                'ffe-grid',
                'ffe-grid-react',
                'ffe-icons',
                'ffe-icons-react',
                'ffe-searchable-dropdown-react',
                'ffe-tables',
                'ffe-radio-button-react',
            ],
        ],
    },
};
