name: build github pages

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    # Run every day at 21:00 UTC
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm buils
      - run: npm run build-storybook
      - name: Deploy to remote
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          target-folder: storybook
          repository-name: sparebank1utvikling/design.sparebank1.no
          branch: develop
          token: ${{ secrets.GH_PAGES_DS_PAT }}
