name: Publish

on:
    push:
        branches:
            - main

jobs:
    publish:
        name: Build and publish npm packages with lerna
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Required for OIDC
            contents: read
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  fetch-depth: '0'
                  ref: 'main'
                  # Use personnel access token for bot account
                  token: ${{ secrets.GH_USER_PAT }}

            - name: git config user
              run: |
                  git config user.email "designsystem@sparebank1.no"
                  git config user.name "sb1-designsystem"

            - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'

            - run: |
                  npm ci --ignore-scripts
                  echo "$GITHUB_WORKSPACE/node_modules/.bin/" >> $GITHUB_PATH

            - name: lerna changed
              id: lerna-changed
              run: echo "CHANGED_COUNT=$(lerna changed|wc -l)" >> $GITHUB_OUTPUT

            - name: Build packages
              if: ${{ steps.lerna-changed.outputs.CHANGED_COUNT > 0 }}
              run: |
                  npm run lint
                  npm run build
                  npm test -- --ci

            - name: lerna publish to registry.npmjs.org
              if: ${{ steps.lerna-changed.outputs.CHANGED_COUNT > 0 }}
              run: lerna publish --yes --no-verify-access --force-git-tag --create-release github --force-publish
              env:
                  GH_TOKEN: ${{ secrets.GH_USER_PAT }}

            - name: Merge back changes to development branch
              if: ${{ steps.lerna-changed.outputs.CHANGED_COUNT > 0 }}
              run: |
                  git checkout develop
                  git pull
                  git merge -X theirs --no-edit main
                  git push origin develop
                  git push --tags

            - name: Build storybook
              if: ${{ steps.lerna-changed.outputs.CHANGED_COUNT > 0 }}
              run: |
                  npm run build
                  npm run build-storybook

            - name: Deploy storybook as gh-pages
              if: ${{ steps.lerna-changed.outputs.CHANGED_COUNT > 0 }}
              uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
              with:
                  folder: storybook-static
                  branch: gh-pages
                  token: ${{ secrets.GH_USER_PAT }}
