name: Sync Figma variables to tokens
on:
    workflow_dispatch:
        inputs:
            file_key:
                description: 'The file key of the Figma file to be updated'
                required: true

jobs:
    sync-figma-to-tokens:
        runs-on: ubuntu-latest
        permissions:
            # Need to be able to create new branches and commits
            contents: write
            pull-requests: write
        steps:
            - name: Install Node.js
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24

            - name: Clone repo
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Validate inputs
              env:
                  FILE_KEY: ${{ github.event.inputs.file_key }}
              run: |
                  if [[ ! "$FILE_KEY" =~ ^[a-zA-Z0-9_-]+$ ]]; then
                      echo "Error: file_key contains invalid characters. Only a-z, A-Z, 0-9, _ and - are allowed."
                      exit 1
                  fi

            - name: Install dependencies
              run: npm ci --ignore-scripts

            - name: Sync variables in Figma file to tokens
              run: npm run sync-figma-to-tokens -- --output packages/ffe-core/tokens
              env:
                  FILE_KEY: ${{ github.event.inputs.file_key }}
                  PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_ACTION_VARIABLES_SYNC_FIGMA_TOKEN }}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
              with:
                  commit-message: 'chore: Update tokens from Figma'
                  title: 'chore: Update tokens from Figma'
                  body: 'Update tokens from Figma from file: https://www.figma.com/file/${{ github.event.inputs.file_key }}'
                  branch: update-tokens
