name: update ffe-icons svgs

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v6
              with:
                  node-version: 24

            - name: Install dependencies
              run: |
                  pwd
                  npm ci --ignore-scripts
              working-directory: packages/ffe-icons

            - name: Build icons
              run: npm run build:icons
              working-directory: packages/ffe-icons

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'fix(ffe-icons): oppdater ikon SVGer'
                  title: 'feat(ffe-icons): oppdater ikon SVGer'
                  body: "BREAKING CHANGE: Oppdaterer SVG'ene i ffe-icons til å passe med de som er tilgjengelige i Material Symbols"
                  branch: 'auto-update-icons'
