name: update ffe-icons svgs

on:
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false

            - name: Setup Node.js
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24

            - name: Install dependencies
              run: |
                  pwd
                  npm ci --ignore-scripts
              working-directory: packages/ffe-icons

            - name: Build icons
              run: npm run build:icons
              working-directory: packages/ffe-icons

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'fix(ffe-icons): oppdater ikon SVGer'
                  title: 'feat(ffe-icons): oppdater ikon SVGer'
                  body: "BREAKING CHANGE: Oppdaterer SVG'ene i ffe-icons til å passe med de som er tilgjengelige i Material Symbols"
                  branch: 'auto-update-icons'
